services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=secure_password
    volumes:
      - /host/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped