networks:
  macvlan_network:
    external: True

services:
  videoinventory:
    build:
      context: /mnt/.ix-apps/docker/myapps/inventor
      dockerfile: /mnt/.ix-apps/docker/myapps/inventor/Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        BUILDKIT_INLINE_CACHE: 1
    image: videoinventory
    container_name: videoinventory-app
    environment:
      - DB_PATH=/db/videoinventory.db
      - DATA_DIRS=/mnt/cluster-01/gaystuff-inbox,/mnt/cluster-01/noforn,/mnt/cluster-01/video-inbox,/mnt/cluster-01/gaystuff-misc,/mnt/cluster-01/video-noforn,/mnt/cluster-01/gaystuff-video,/mnt/cluster-01/video-web,/mnt/cluster-01/video-youtube,/mnt/cluster-02/gstf-ng-video,/mnt/cluster-02/gstf-ng-video2,/mnt/cluster-02/gstf-ng-video3
      - MAX_SECTION_DEPTH=4
      - THREAD_COUNT=4
      - LOG_DIR=/logs
      - DEBUG=1
    deploy:
      resources:
        limits:
          cpus: '4.0'
        reservations:
          cpus: '2.0'
    networks:
      macvlan_network:
        ipv4_address: 10.121.124.50
    ports:
      - "80:80"
    restart: always
    volumes:
      - /mnt:/mnt
      - /mnt/.ix-apps/docker/myapps/inventor/db:/db
      - /mnt/.ix-apps/docker/myapps/inventor/logs:/logs